apiVersion: apps/v1
kind: Deployment
metadata:
  name: dyrectorio-k8s-agent
  namespace: dyrectorio
  labels:
    app: dyrectorio-k8s-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dyrectorio-k8s-agent
  template:
    metadata:
      labels:
        app: dyrectorio-k8s-agent
    spec:
      initContainers:
        - name: crane-init
          image: ghcr.io/dyrector-io/dyrectorio/agent/crane:0-3-prometheus
          command:
            - crane
            - init
          imagePullPolicy: Always
          resources:
            requests:
              memory: 128Mi
            limits:
              cpu: 1
              memory: 256Mi
          envFrom:
            - configMapRef:
                name: crane-config
      containers:
        - name: crane
          image: ghcr.io/dyrector-io/dyrectorio/agent/crane:0-3-prometheus
          imagePullPolicy: Always
          resources:
            requests:
              memory: 128Mi
            limits:
              cpu: 1
              memory: 256Mi
          envFrom:
            - configMapRef:
                name: crane-config
            - secretRef:
                name: dyrectorio-secret

