version: "3.7"
services:
  dagent-go:
    image: ghcr.io/dyrector-io/dyrectorio/dagent:latest
    container_name: dagent-go
    ports:
      - 9923:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/dagent:/srv/dagent
    env_file:
      - ./.env
