# this file is for development,
# when crux and crux-ui is executed locally using NodeJS
version: "3.3"
services:
  crux-postgres:
    container_name: crux-postgres
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-crux}
      POSTGRES_PASSWORD: ${CRUX_POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-crux}
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - crux-intranet
  kratos-postgres:
    container_name: crux-kratos-postgres
    image: postgres:13.3-alpine3.14
    environment:
      - POSTGRES_PASSWORD=${KRATOS_POSTGRES_PASSWORD}
      - POSTGRES_USER=kratos
      - POSTGRES_DB=kratos
    restart: unless-stopped
    volumes:
      - kratos-db:/var/lib/postgresql/data
    networks:
      - crux-intranet
  kratos-migrate:
    container_name: crux-kratos-migrate
    image: ghcr.io/dyrector-io/dyrectorio/web/kratos:${DYO_VERSION}
    depends_on:
      - kratos-postgres
    environment:
      - SQA_OPT_OUT=true
      - DSN=postgres://kratos:${KRATOS_POSTGRES_PASSWORD}@kratos-postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    command: -c /etc/config/kratos/kratos.yaml migrate sql -e --yes
    networks:
      - crux-intranet
  kratos:
    container_name: crux-kratos
    image: ghcr.io/dyrector-io/dyrectorio/web/kratos:${DYO_VERSION}
    build:
      context: ./kratos
    depends_on:
      kratos-migrate:
        condition: service_completed_successfully
    platform: linux/amd64
    ports:
      - 4433:4433 # public
      #Â WARNING: Do NOT expose the admin port in production!
      - 4434:4434 # admin
    environment:
      - KRATOS_ADMIN_URL=${KRATOS_ADMIN_URL:-http://172.17.0.1:4434}
      - KRATOS_URL=${KRATOS_URL:-http://172.17.0.1:8000/kratos}
      - CRUX_UI_URL=${CRUX_UI_URL:-http://172.17.0.1:8000}
      - DEV=${KRATOS_DEV:-false}
      - SQA_OPT_OUT=true
      - DSN=postgres://kratos:${KRATOS_POSTGRES_PASSWORD}@kratos-postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=${KRATOS_LOG_LEVEL}
      - LOG_LEAK_SENSITIVE_VALUES=${KRATOS_LOG_LEAK_SENSITIVE_VALUES}
      - SECRETS_COOKIE=${COOKIE_SECRET}
      - COURIER_SMTP_CONNECTION_URI=${SMTP_URI}
    restart: unless-stopped
    command: serve -c /etc/config/kratos/kratos.yaml --watch-courier
    labels:
      - traefik.enable=true
      - traefik.http.routers.kratos.rule=Host(`${TRAEFIK_HOST:-172.17.0.1}`) && PathPrefix(`/kratos`)
      - traefik.http.routers.kratos.entrypoints=web
      - traefik.http.services.kratos.loadbalancer.server.port=4433
      - traefik.http.middlewares.kratos-strip.stripprefix.prefixes=/kratos
      - traefik.http.routers.kratos.middlewares=kratos-strip
    networks:
      - crux-intranet
  mailslurper:
    container_name: crux-mailslurper
    restart: unless-stopped
    image: oryd/mailslurper:latest-smtps
    ports:
      - 1025:1025
      - 4436:4436
      - 4437:4437
    networks:
      - crux-intranet
  crux-traefik:
    container_name: crux-traefik
    image: traefik:v2.8
    restart: unless-stopped
    depends_on:
      - kratos
    platform: linux/amd64
    ports:
      - 8000:8000
      - 8080:8080 # web ui
    command:
      - --log.level=INFO
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.filename=/etc/traefik/traefik.dev.yml
      - --entrypoints.web.address=:8000
    environment:
      - TRAEFIK_HOST=${TRAEFIK_HOST:-172.17.0.1}
    volumes:
      - ./traefik.dev.yml:/etc/traefik/traefik.dev.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - crux-intranet
volumes:
  kratos-db:
networks:
  crux-intranet:
    name: crux-intranet
